resources:
  # Platform resource limits tuning - required for high concurrency with scheduled jobs
  - sas-scheduler/resource-limits.yaml

transformers:
  # Platform resource limits tuning - required for high concurrency with scheduled jobs
  - sas-scheduler/resource-limits.yaml
