---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-folders-resource-limits-tuning
patch: |-
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: 3000m
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 2Gi
target:
  group: apps
  kind: Deployment
  name: sas-folders
  version: v1
