resources:
  # Platform services resource limits tuning
  - sas-files/resource-limits.yaml

  # Report Services resource limits tuning
  - sas-report-execution/resource-limits.yaml

  # Visual Analytics services resource limits tuning
  - sas-visual-analytics-app/resource-limits.yaml

transformers:
  # Platform services resource limits tuning
  - sas-files/resource-limits.yaml

  # Report Services resource limits tuning
  - sas-report-execution/resource-limits.yaml

  # Visual Analytics services resource limits tuning
  - sas-visual-analytics-app/resource-limits.yaml
