resources:
  # Model Management Services tuning
  - sas-model-manager/resource-limits.yaml
  - sas-score-definitions/resource-limits.yaml

transformers:
  # Model Management Services tuning
  - sas-model-manager/resource-limits.yaml
  - sas-score-definitions/resource-limits.yaml
