---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-job-execution-resource-limits-tuning
patch: |-
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: 2000m
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 1500Mi
target:
  group: apps
  kind: Deployment
  name: sas-job-execution
  version: v1
