resources:
  # Compute/Launcher tuning
  - sas-compute/resource-limits.yaml
  - sas-launcher/launcher-super-user-process-limit.yaml
  - sas-launcher/launcher-user-process-limit.yaml

  # Job Execution tuning
  - sas-job-execution/resource-limits.yaml

  # SAS Studio tuning
  - sas-studio/resource-limits.yaml
  - sas-studio-app/resource-limits.yaml

  # - kube-proxy/node-kubelet-updater.yaml

  # Workload Orchestrator tuning
  - sas-workload-orchestrator/resource-limits.yaml

transformers:
  # Compute/Launcher tuning
  - sas-compute/resource-limits.yaml
  - sas-launcher/launcher-super-user-process-limit.yaml
  - sas-launcher/launcher-user-process-limit.yaml

  # Job Execution tuning
  - sas-job-execution/resource-limits.yaml

  # SAS Studio tuning
  - sas-studio/resource-limits.yaml
  - sas-studio-app/resource-limits.yaml

  # Workload Orchestrator tuning
  - sas-workload-orchestrator/resource-limits.yaml