---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-scheduler-resource-limits-tuning
patch: |-
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: 1500Mi
target:
  group: apps
  kind: Deployment
  name: sas-scheduler
  version: v1
