resources:
  # Platform resource limits tuning
  - sas-arke/resource-limits.yaml
  - sas-authorization/resource-limits.yaml
  - sas-files/resource-limits.yaml
  - sas-folders/resource-limits.yaml
  - sas-logon-app/resource-limits.yaml

transformers:
  # Platform resource limits tuning
  - sas-arke/resource-limits.yaml
  - sas-authorization/resource-limits.yaml
  - sas-files/resource-limits.yaml
  - sas-folders/resource-limits.yaml
  - sas-logon-app/resource-limits.yaml
