resources:
  # Platform resource limits tuning
  - sas-file-store/resource-limits.yaml
  - sas-logon-app/resource-limits.yaml

transformers:
  # Platform resource limits tuning
  - sas-file-store/resource-limits.yaml
  - sas-logon-app/resource-limits.yaml
